version: "3"
services:
  caddy:
    image: abiosoft/caddy:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - magick8sball
    volumes:
      - ${PWD}/Caddyfile:/etc/Caddyfile
      - ${PWD}/.caddy:/root/.caddy
  api:
    image: carolynvs/magick8sball:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - magick8sball
networks:
  magick8sball:
