# Site settings
title: "magick8sball.io"
email: "roflynnc@microsoft.com"
description: > # this means to ignore newlines until "baseurl:"
  magick8sball.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://magick8sball.io" # the base hostname & protocol for your site
twitter_username: deislabs
github_username:  deislabs

magick8sball_url: /api

# Build settings
markdown: kramdown
include: ['.htaccess']
exclude: [docs, vendor, script, node_modules, Gruntfile.js, Gemfile, Gemfile.lock, package.json, s3_website.yml, gulpfile.js, README.md, Dockerfile, Makefile, magick8sball]
