# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  registry: deislabs

steps:
- script: REGISTRY=$(registry) make build
  displayName: 'Build Docker Images'
- task: Docker@1
  displayName: Login
  inputs:
    containerRegistryType: Container Registry
    dockerRegistryEndpoint: deislabs-registry
    command: login
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
- script: REGISTRY=$(registry) make push
  displayName: 'Publish Docker Images'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
